/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.servirjanuaria.amauri.apresentacao;

import br.com.servirjanuaria.amauri.dataAccess.AlunoDAO;
import br.com.servirjanuaria.amauri.dataAccess.BairroDAO;
import br.com.servirjanuaria.amauri.dataAccess.CertidaoNascimentoDAO;
import br.com.servirjanuaria.amauri.dataAccess.EnderecoDAO;
import br.com.servirjanuaria.amauri.domainModel.Aluno;
import br.com.servirjanuaria.amauri.domainModel.Bairro;
import br.com.servirjanuaria.amauri.domainModel.CertidaoNascimento;
import br.com.servirjanuaria.amauri.domainModel.Endereco;
import br.com.servirjanuaria.amauri.domainModel.repositorios.AlunoRepositorio;
import br.com.servirjanuaria.amauri.domainModel.repositorios.BairroRepositorio;
import br.com.servirjanuaria.amauri.domainModel.repositorios.CertidaoNascimentoRepositorio;
import br.com.servirjanuaria.amauri.domainModel.repositorios.EnderecoRepositorio;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author amauri_pereira
 */
public class GestaoAlunoTela1JInternalFrame extends javax.swing.JInternalFrame {

    private static JDesktopPane painelPrincipal = null;

    /*Declaração de Variáveis*/
    static AlunoRepositorio alunos = new AlunoDAO();
    static EnderecoRepositorio enderecos = new EnderecoDAO();
    static CertidaoNascimentoRepositorio certidoes = new CertidaoNascimentoDAO();

    /*Instaciando variáveis*/
    Aluno aluno = new Aluno();
    CertidaoNascimento certidaoNascimento = new CertidaoNascimento();
    Endereco endereco = new Endereco();

    /**
     * Creates new form GestaoAlunoTela1JInternalFrame
     *
     * @param painelPrincipal
     */
    public GestaoAlunoTela1JInternalFrame(JDesktopPane painelPrincipal) {
        initComponents();
        this.populaCmbBairro();
        GestaoAlunoTela1JInternalFrame.painelPrincipal = painelPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //Metodo que add todos os projetos cadastrados na ComboBoxBairro
    private void populaCmbBairro() {

        Bairro bairro = new Bairro();
        BairroRepositorio bairros = new BairroDAO();
        cmbBairro.removeAllItems();
        cmbBairro.addItem("Selecione");

        for (Bairro bairroItem : bairros.buscar(bairro)) {
            cmbBairro.addItem(bairroItem.getNome());
        }

    }

    public void dadosFormularioCadastraAluno() {

        /*Capturando os valores dos campos para as variáveis.*/
        String nome = txtNome.getText();
        String dataNascimento = txtDataNascimento.getText();
        String rg = txtRG.getText();
        String cpf = txtCPF.getText();
        String sexo = cmbSexo.getSelectedItem().toString();
        String nacionalidade = txtNacionalidade.getText();
        String cidadeNascimento = txtCidadeNascimento.getText();
        String etnia = cmbEtnia.getSelectedItem().toString();
        String estado = cmbEstado.getSelectedItem().toString();
        String numeroCertidaoNascimento = txtCertidaoNascimento.getText();
        String livro = txtLivro.getText();
        String folha = txtFolha.getText();
        String gr = txtGR.getText();
        String rua = txtRua.getText();
        String numero = txtNumero.getText();
        String bairro = cmbBairro.getSelectedItem().toString();
        String cidade = txtCidade.getText();
        String complemento = txtComplemento.getText();
        String cep = txtCep.getText();
        String codigoConsumidorCopasa = txtCodigoConsumidorCopasa.getText();
        System.out.println(sexo);
        System.out.println(rg);
        System.out.println(cpf);

        try {

            /*Setando valores nos objetos temporarios: CERTIDÃO DE NASCIMENTO */
            certidaoNascimento.setNumero(Integer.parseInt(numeroCertidaoNascimento));
            certidaoNascimento.setLivro(Integer.parseInt(livro));
            certidaoNascimento.setFolha(Integer.parseInt(folha));
            certidaoNascimento.setGR(Integer.parseInt(gr));

            /*Setando valores nos objetos temporarios: ENDEREÇO */
            endereco.setNumero(numero);
            endereco.setRua(rua);
            Bairro bairroSelecionado = new Bairro();
            bairroSelecionado.setNome(bairro);

            BairroRepositorio bairros = new BairroDAO();
            for (Bairro bairroEncontrado : bairros.buscar(bairroSelecionado)) {
                endereco.setBairro(bairroEncontrado);
            }

            endereco.setComplemento(complemento);
            endereco.setCidade(cidade);
            endereco.setCep(cep);
            endereco.setCodigoConsumidor(codigoConsumidorCopasa);

            /*Setando valores nos objetos temporarios: ALUNO */
            aluno.setNome(nome);
            aluno.setDataNascimento(formatData(dataNascimento));
            aluno.setRg(rg);
            aluno.setCpf(cpf);
            aluno.setSexo(sexo);
            aluno.setNacionalidade(nacionalidade);
            aluno.setCidadeNascimento(cidadeNascimento);
            aluno.setEstado(estado);
            aluno.setEtnia(etnia);
            aluno.setEndereco(endereco);
            aluno.setCertidaoNascimento(certidaoNascimento);
            aluno.setPessoa(aluno);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Salvar Aluno", JOptionPane.ERROR_MESSAGE);

        }

    }

    public static Date formatData(String dataString) throws Exception {
        if (dataString == null || dataString.equals("")) {
            return null;
        }

        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        java.sql.Date data = new java.sql.Date(dateFormat.parse(dataString).getTime());

        return data;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnGeral = new javax.swing.JPanel();
        jpnEnderecoAluno = new javax.swing.JPanel();
        lblRua = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblbairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        lblCodigoConsumidorCopasa = new javax.swing.JLabel();
        txtCodigoConsumidorCopasa = new javax.swing.JTextField();
        cmbBairro = new javax.swing.JComboBox();
        btnAddBairro = new javax.swing.JButton();
        txtCep = new javax.swing.JFormattedTextField();
        jpnIndentificacaoAluno = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox();
        lblEstado = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        lblEtnia = new javax.swing.JLabel();
        cmbEtnia = new javax.swing.JComboBox();
        lblNacionalidade = new javax.swing.JLabel();
        txtNacionalidade = new javax.swing.JTextField();
        lblRG = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblCertidaoNascimento = new javax.swing.JLabel();
        lblLivro = new javax.swing.JLabel();
        txtCertidaoNascimento = new javax.swing.JTextField();
        lblGR = new javax.swing.JLabel();
        txtLivro = new javax.swing.JTextField();
        lblFolha = new javax.swing.JLabel();
        txtFolha = new javax.swing.JTextField();
        txtGR = new javax.swing.JTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        lblCidadeNascimento = new javax.swing.JLabel();
        txtCidadeNascimento = new javax.swing.JTextField();
        txtRG = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox();
        jpnFotoGeral = new javax.swing.JPanel();
        btnUploadFoto = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();
        btnRemoverFoto = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        btnAvancar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Matrícula de Aluno");

        jpnEnderecoAluno.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço do Aluno (a)"));

        lblRua.setText("Rua, Avenida, Travessa: ");

        lblNumero.setText("Número:");

        lblbairro.setText("Bairro:");

        lblCidade.setText("Cidade:");

        lblComplemento.setText("Complemento:");

        lblCep.setText("Cep:");

        lblCodigoConsumidorCopasa.setText("Código Consumidor Copasa: ");

        cmbBairro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbBairroFocusGained(evt);
            }
        });

        btnAddBairro.setText("+");
        btnAddBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBairroActionPerformed(evt);
            }
        });

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jpnEnderecoAlunoLayout = new javax.swing.GroupLayout(jpnEnderecoAluno);
        jpnEnderecoAluno.setLayout(jpnEnderecoAlunoLayout);
        jpnEnderecoAlunoLayout.setHorizontalGroup(
            jpnEnderecoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnEnderecoAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnEnderecoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnEnderecoAlunoLayout.createSequentialGroup()
                        .addGroup(jpnEnderecoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComplemento))
                        .addGap(18, 18, 18)
                        .addGroup(jpnEnderecoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCep)
                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnEnderecoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnEnderecoAlunoLayout.createSequentialGroup()
                                .addComponent(lblCodigoConsumidorCopasa)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCodigoConsumidorCopasa)))
                    .addGroup(jpnEnderecoAlunoLayout.createSequentialGroup()
                        .addGroup(jpnEnderecoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRua))
                        .addGap(18, 18, 18)
                        .addGroup(jpnEnderecoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnEnderecoAlunoLayout.createSequentialGroup()
                                .addComponent(lblNumero)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtNumero)))
                    .addGroup(jpnEnderecoAlunoLayout.createSequentialGroup()
                        .addGroup(jpnEnderecoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblbairro)
                            .addGroup(jpnEnderecoAlunoLayout.createSequentialGroup()
                                .addComponent(cmbBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jpnEnderecoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnEnderecoAlunoLayout.createSequentialGroup()
                                .addComponent(lblCidade)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCidade))))
                .addContainerGap())
        );
        jpnEnderecoAlunoLayout.setVerticalGroup(
            jpnEnderecoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnEnderecoAlunoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnEnderecoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRua)
                    .addComponent(lblNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnEnderecoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnEnderecoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbairro)
                    .addComponent(lblCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnEnderecoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddBairro))
                .addGap(18, 18, 18)
                .addGroup(jpnEnderecoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplemento)
                    .addComponent(lblCep)
                    .addComponent(lblCodigoConsumidorCopasa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnEnderecoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoConsumidorCopasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jpnIndentificacaoAluno.setBorder(javax.swing.BorderFactory.createTitledBorder("Indentificação do Aluno (a)"));

        lblNome.setText("Nome:");

        lblSexo.setText("Sexo:");

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Masculino", "Feminino" }));

        lblEstado.setText("Estado:");

        lblDataNascimento.setText("Data de Nascimento:");

        lblEtnia.setText("Etnia:");

        cmbEtnia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção:", "Branca", "Preta", "Parda", "Amarela", "Indígena", "Não Declarada" }));

        lblNacionalidade.setText("Nacionalidade:");

        lblRG.setText("RG:");

        lblCPF.setText("CPF:");

        lblCertidaoNascimento.setText("Certidão de Nascimento:");

        lblLivro.setText("Livro:");

        lblGR.setText("GR:");

        lblFolha.setText("Folha:");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblCidadeNascimento.setText("Cidade de Nascimento:");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um estado:", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        javax.swing.GroupLayout jpnIndentificacaoAlunoLayout = new javax.swing.GroupLayout(jpnIndentificacaoAluno);
        jpnIndentificacaoAluno.setLayout(jpnIndentificacaoAlunoLayout);
        jpnIndentificacaoAlunoLayout.setHorizontalGroup(
            jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnIndentificacaoAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnIndentificacaoAlunoLayout.createSequentialGroup()
                        .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDataNascimento))
                        .addGap(18, 18, 18)
                        .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRG)
                            .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCPF))
                        .addGap(18, 18, 18)
                        .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnIndentificacaoAlunoLayout.createSequentialGroup()
                                .addComponent(lblCidadeNascimento)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCidadeNascimento)))
                    .addGroup(jpnIndentificacaoAlunoLayout.createSequentialGroup()
                        .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpnIndentificacaoAlunoLayout.createSequentialGroup()
                                .addComponent(lblSexo)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnIndentificacaoAlunoLayout.createSequentialGroup()
                        .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbEtnia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpnIndentificacaoAlunoLayout.createSequentialGroup()
                                .addComponent(lblEtnia)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNacionalidade))
                        .addGap(18, 18, 18)
                        .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpnIndentificacaoAlunoLayout.createSequentialGroup()
                                .addComponent(lblEstado)
                                .addGap(156, 156, 156))
                            .addComponent(cmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpnIndentificacaoAlunoLayout.createSequentialGroup()
                        .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCertidaoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCertidaoNascimento))
                        .addGap(18, 18, 18)
                        .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLivro)
                            .addGroup(jpnIndentificacaoAlunoLayout.createSequentialGroup()
                                .addComponent(lblLivro)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFolha, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFolha))
                        .addGap(18, 18, 18)
                        .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGR)
                            .addComponent(txtGR, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jpnIndentificacaoAlunoLayout.setVerticalGroup(
            jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnIndentificacaoAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNascimento)
                    .addComponent(lblRG)
                    .addComponent(lblCPF)
                    .addComponent(lblCidadeNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidadeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEtnia)
                    .addComponent(lblNacionalidade)
                    .addComponent(lblEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEtnia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCertidaoNascimento)
                    .addComponent(lblFolha)
                    .addComponent(lblGR)
                    .addComponent(lblLivro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnIndentificacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtLivro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtGR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCertidaoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jpnFotoGeral.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto do Aluno"));

        btnUploadFoto.setText("Upload");
        btnUploadFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadFotoActionPerformed(evt);
            }
        });

        btnRemoverFoto.setText("Excuir");
        btnRemoverFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnFotoGeralLayout = new javax.swing.GroupLayout(jpnFotoGeral);
        jpnFotoGeral.setLayout(jpnFotoGeralLayout);
        jpnFotoGeralLayout.setHorizontalGroup(
            jpnFotoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFotoGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnFotoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUploadFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoverFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnFotoGeralLayout.setVerticalGroup(
            jpnFotoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnFotoGeralLayout.createSequentialGroup()
                .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUploadFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemoverFoto)
                .addGap(6, 6, 6))
        );

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnAvancar.setText("Avançar");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnGeralLayout = new javax.swing.GroupLayout(jpnGeral);
        jpnGeral.setLayout(jpnGeralLayout);
        jpnGeralLayout.setHorizontalGroup(
            jpnGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnEnderecoAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnGeralLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpnGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnGeralLayout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnGeralLayout.createSequentialGroup()
                                .addComponent(jpnFotoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpnIndentificacaoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jpnGeralLayout.setVerticalGroup(
            jpnGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnFotoGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnIndentificacaoAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnEnderecoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizar)
                    .addComponent(btnAvancar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBairroActionPerformed
        this.populaCmbBairro();
        CadastroBairroJInternalFrame cadastroBairroJInternalFrame = new CadastroBairroJInternalFrame(painelPrincipal);
        cadastroBairroJInternalFrame.setVisible(true);
        painelPrincipal.add(cadastroBairroJInternalFrame);
        cadastroBairroJInternalFrame.toFront();
    }//GEN-LAST:event_btnAddBairroActionPerformed

    private void btnUploadFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadFotoActionPerformed
        try {
            JFileChooser busca_foto = new JFileChooser();
            busca_foto.setCurrentDirectory(new File("C:\\Users\\Amauri\\Desktop\\Gerencia de Projeto"));
            busca_foto.setDialogTitle("Carregar foto do Aluno");
            busca_foto.showOpenDialog(this);
            String foto = "" + busca_foto.getSelectedFile().getName();

            System.out.println(foto);
            lblFoto.setLocation(0, 0);// trecho de codigo para centralizar a imagem o label.
            lblFoto.setIcon(new ImageIcon("C:\\Users\\Amauri\\Desktop\\Gerencia de Projeto\\" + foto));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Carregar foto", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUploadFotoActionPerformed

    private void btnRemoverFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverFotoActionPerformed
        //lblFoto.setText("");
    }//GEN-LAST:event_btnRemoverFotoActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        try {
            /* if (!"".equals(txtRua.getText()) || !"".equals(txtNumero.getText()) || !"".equals(txtCidade.getText()) || !"".equals(cmbSexo.getSelectedItem().toString())) {
             if (!"".equals(txtNome.getText()) || !"".equals(cmbSexo.getSelectedItem().toString()) || !"".equals(txtDataNascimento.getText()) || !"".equals(txtCidadeNascimento.getText()) || !"".equals(cmbEtnia.getSelectedItem().toString())) {
                    
             */
            dadosFormularioCadastraAluno();
            enderecos.salvar(endereco);
            certidoes.salvar(certidaoNascimento);
            alunos.salvar(aluno);
            this.dispose();

            /*  } else {
             JOptionPane.showMessageDialog(null, "Os campos: " + lblNome.getName() + " ," + lblSexo.getName() + " ," + lblDataNascimento.getName() + " ," + lblEtnia.getName() + " ," + lblCidadeNascimento.getName() + " não podem ficar em branco!", "Campos em Branco", JOptionPane.ERROR_MESSAGE);
             }
             } else {
             JOptionPane.showMessageDialog(null, "Os campos: " + lblRua.getName() + " ," + lblNumero.getName() + " ," + lblCidade.getName() + " ," + lblSexo.getName() + " não podem ficar em branco!", "Campos em Branco", JOptionPane.ERROR_MESSAGE);
             }*/
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Finalizar cadastro: tela 1", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        try {
            /* if (!"".equals(txtRua.getText()) || !"".equals(txtNumero.getText()) || !"".equals(txtCidade.getText()) || !"".equals(txtNumero.getText())) {
             //   if (!"".equals(txtNome.getText()) || !"".equals(cmbSexo.getSelectedItem().toString()) || !"".equals(txtDataNascimento.getText()) || !"".equals(txtCidadeNascimento.getText())) {
             */
            dadosFormularioCadastraAluno();
            GestaoAlunoTela2JInternalFrame gestaoAlunoTela2JInternalFrame = new GestaoAlunoTela2JInternalFrame(GestaoAlunoTela1JInternalFrame.painelPrincipal, aluno, certidaoNascimento, endereco);
            gestaoAlunoTela2JInternalFrame.setVisible(true);
            painelPrincipal.add(gestaoAlunoTela2JInternalFrame);
            gestaoAlunoTela2JInternalFrame.toFront();
            /* } else {
             JOptionPane.showMessageDialog(null, "Os campos: " + lblNome.getText() + " ," + lblSexo.getText() + " ," + lblDataNascimento.getText() + " ," + lblEtnia.getText() + " ," + lblCidadeNascimento.getText() + " não podem ficar em branco!", "Campos em Branco", JOptionPane.ERROR_MESSAGE);
             }
             } else {
             JOptionPane.showMessageDialog(null, "Os campos: " + lblRua.getText() + " ," + lblNumero.getText() + " ," + lblCidade.getText() + " ," + lblSexo.getText() + " não podem ficar em branco!", "Campos em Branco", JOptionPane.ERROR_MESSAGE);
             }*/
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Tela 1", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar?", "Cadastro Bairro", JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbBairroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbBairroFocusGained
        populaCmbBairro();
    }//GEN-LAST:event_cmbBairroFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBairro;
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnRemoverFoto;
    private javax.swing.JButton btnUploadFoto;
    private javax.swing.JComboBox cmbBairro;
    private javax.swing.JComboBox cmbEstado;
    private javax.swing.JComboBox cmbEtnia;
    private javax.swing.JComboBox cmbSexo;
    private javax.swing.JPanel jpnEnderecoAluno;
    private javax.swing.JPanel jpnFotoGeral;
    private javax.swing.JPanel jpnGeral;
    private javax.swing.JPanel jpnIndentificacaoAluno;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCertidaoNascimento;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCidadeNascimento;
    private javax.swing.JLabel lblCodigoConsumidorCopasa;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEtnia;
    private javax.swing.JLabel lblFolha;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblGR;
    private javax.swing.JLabel lblLivro;
    private javax.swing.JLabel lblNacionalidade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblbairro;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCertidaoNascimento;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCidadeNascimento;
    private javax.swing.JTextField txtCodigoConsumidorCopasa;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtFolha;
    private javax.swing.JTextField txtGR;
    private javax.swing.JTextField txtLivro;
    private javax.swing.JTextField txtNacionalidade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables

}
